### ISSUE TITLE
Can't build in XCode 6.1.1 (iOS 8.1)

### ISSUE THREAD

**Issue by thanhcuong1990** [cbpowell/MarqueeLabel-Swift#1]
I'm try to build this project in XCode 6.1.1 but i got many issue. Please check it. 
Thanks.

**Comment by cbpowell** [comment]
Unfortunately, MarqueeLabel-Swift is very out of date. I added a note to the README about the status, until I get around to updating things. Meanwhile, please use the Objective-C version of MarqueeLabel, or help out by submitting fixes!
