### ISSUE TITLE
 MarqueeLabel.swift Line 1264 Thread 1: EXC_BAD_ACCESS (code=2, address=0x7fff4f8daff8)

### ISSUE THREAD

**Issue by piacaro** [cbpowell/MarqueeLabel-Swift#12]
I was trying to run your Demo and I got the Error message. I already downloaded the Beta Xcode with swift 2.0. Please could you help?

**Comment by cbpowell** [comment]
I _thought_ I had fixed this, but then I actually reverted the commit that fixed it! (See my last comment in #11)

This should be re-fixed now with commit 3c68b5d. Thanks!
