### ISSUE TITLE
One MarqueeLabel is not scrolling

### ISSUE THREAD

**Issue by Bjqrn88** [cbpowell/MarqueeLabel-Swift#14]
I have a UITableView that i populate like this:

``` swift
//Insert values in tableView
func tableView(tableView: UITableView, cellForRowAtIndexPath indexPath: NSIndexPath) -> UITableViewCell {
         let customCell = myTableView.dequeueReusableCellWithIdentifier("customCell") as! DetailCell
         let cell = UITableViewCell(style: UITableViewCellStyle.Value1, reuseIdentifier: "")
         if values != nil{
            let labelWidth: CGFloat = 260.0
            let font = UIFont(name: "Helvetica Neue", size: 17.0)
            let att = [NSFontAttributeName:font!]
            let text = values![indexPath.row].text as NSString
            let size = text.sizeWithAttributes(att)

          if size.width > labelWidth{
                customCell.customLabel.tag = scrollTag++
                customCell.customLabel.type = .Continuous
                customCell.customLabel.animationCurve = .EaseIn
                customCell.customLabel.text = values![indexPath.row].text
                customCell.customLabel.leadingBuffer = 5.0
                customCell.customLabel.trailingBuffer = 25.0
                return customCell
          }else{
              cell.textLabel?.text = values![indexPath.row].text
              return cell
          }
      }
      return cell
 }
```

And this works just fine, for some of the cells.. 
But i have one cell that is 261.xx i width, and this cell will not start scrolling

Can anyone tell me why..

**Comment by cbpowell** [comment]
Is `cell.textLabel` just a normal UILabel? It seems like you're manually making the decision on whether or not to use a MarqueeLabel instance based on your 260.0 pt width threshold - is this the case?

Unless you have another specific reason to do this, you could just have everything be a MarqueeLabel. MarqueeLabel will automatically scroll if the `text` length (with the specific font, size, etc) is larger than it's frame width, you don't need to perform the length check yourself. If the text is short enough that it can be completely displayed without scrolling, it will look like a normal UILabel and not trigger a scroll animation.

I expect the text in your 261.xx width cell is fitting within the frame of the MarqueeLabel, so as a result it won't scroll.

**Comment by Bjqrn88** [comment]
Thanks for the good advice.. 

It turned out that the MarqueeLabel I was using was bigger then the table.. Dohh!
So I fixed that, and then change code to this:

```
 //Insert values in tableView
 func tableView(tableView: UITableView, cellForRowAtIndexPath indexPath: NSIndexPath) -> UITableViewCell {
        let customCell = myTableView.dequeueReusableCellWithIdentifier("customCell") as! DetailCell
        if values != nil{
            customCell.customLabel.tag = scrollTag++
            customCell.customLabel.type = .Continuous
            customCell.customLabel.animationCurve = .EaseIn
            customCell.customLabel.text = values![indexPath.row].text
            customCell.customLabel.leadingBuffer = 5.0
            customCell.customLabel.trailingBuffer = 25.0
            return customCell
        }
        return customCell
 }
```

And it works like a charme :+1:

**Comment by cbpowell** [comment]
Awesome!
