### ISSUE TITLE
Does not compile for Swift 1.2

### ISSUE THREAD

**Issue by cyrilzakka** [cbpowell/MarqueeLabel-Swift#2]
I fixed the issues concerning optionals to the best of my abilities but I can't seem to fix the last function with the CGPoint and int i. Any idea on when you'll get around to updating this? I've heard great things :)

**Comment by cbpowell** [comment]
That's actually where I stopped too - I'll probably fix it up in the next week or so! This Swift version is also a little behind the Objective-C version feature-wise, which I'll want to update.

In the interim though, you can always use the Obj-C version in your Swift project! You'll just [need to create a bridging header](https://developer.apple.com/library/ios/documentation/Swift/Conceptual/BuildingCocoaApps/MixandMatch.html), which Xcode can actually do for you (haven't tried it myself, though).

**Comment by cbpowell** [comment]
With the latest batch of commits, MarqueeLabel-Swift should be building in Swift 1.2!
