### ISSUE TITLE
Text Not Visible/Offset to the left

### ISSUE THREAD

**Issue by yoiang** [cbpowell/MarqueeLabel-Swift#23]
Hey @cbpowell ! I love the control!

I've run into an issue using it just recently where all text is offset what appears to be the width of the text, perhaps + any lead or trailing, to the left of the control and thus not visible. There are hacky ways to reset it out of this state.

I've got as far as tracking down so far that `keyFrameAnimationForGradient` expects `awayOffset` to be non-zero but in this situation `awayOffset` begins with a zero value.

**Comment by cbpowell** [comment]
Glad you find it useful!

Would you be able to post an example label configuration (or a demo project) that shows the issue? I can't say I've seen it happen, although I do know that if you look at a MarqueeLabel in Xcode's live layer view debugging feature (I can't remember the name), the labels always look way off to the left - but they render just fine in-app.

**Comment by cbpowell** [comment]
@yoiang, did you ever get any further with this issue? Having an `awayOffset` of zero is odd, as that means you have like a zero-width label or something...

**Comment by cbpowell** [comment]
Going to close this issue for now - can reopen if you can provide some further info!

**Comment by yoiang** [comment]
hey @cbpowell ! Sorry for the late response, I wasn't able to build an isolated repro and as a workaround we labelize and then unlabelize the view. That's good to know about the zero-width, perhaps at some point in the container view's starting lifecycle it itself is undersized and that's sizing the MarqueeLabel to zero.
