### ISSUE TITLE
cant import to swift project "import MarqueeLabel-Swift"

### ISSUE THREAD

**Issue by szuniverse** [cbpowell/MarqueeLabel-Swift#30]
HI

due to the - character I cant import MarqueeLabel-Swift.

What I should do?

![screen shot 2016-03-26 at 12 23 08 pm](https://cloud.githubusercontent.com/assets/7426176/14059761/b6519bfc-f34d-11e5-8b74-9f2541501dfc.png)

**Comment by szuniverse** [comment]
okey I found the solution:
import MarqueeLabel_Swift

**Comment by cbpowell** [comment]
Ah yeah, sorry about the confusion. I should note that in the Readme.
