### ISSUE TITLE
Speed issue of label

### ISSUE THREAD

**Issue by Ashish12425** [cbpowell/MarqueeLabel-Swift#32]
Speed of marquee label in cell increases as much times I reload the tableview .

**Comment by cbpowell** [comment]
@Ashish12425 This version of MarqueeLabel is no longer being updated. Please use the [combined Swift and Objective-C MarqueeLabel](https://github.com/cbpowell/MarqueeLabel) version instead! You may be running into an issue which has already been fixed.

Additionally, that repo contains an [example UITableView usage](https://github.com/cbpowell/MarqueeLabel/blob/master/MarqueeLabelSwift/MarqueeLabelTableViewController.swift) to cross-check against your own implementation (for things like cell reuse).

**Comment by Ashish12425** [comment]
@cbpowell  even after updating the MarqueeLabel speed the scroll speed of label goes on multiplying.
