### ISSUE TITLE
Label is throwing an exception

### ISSUE THREAD

**Issue by cyrilzakka** [cbpowell/MarqueeLabel-Swift#4]
And I have no idea what I'm doing wrong. I linked the QuartzCore framework, imported it and then declared my label as so:  @IBOutlet weak var songNameLabel: MarqueeLabel!
then added the following properties in viewDidLoad 
songNameLabel.type = .Continuous
songNameLabel.scrollDuration = 8.0
songNameLabel.fadeLength = 15.0
but the app crashes and it shows an error at songNameLabel.type = .Continuous :(
Any ideas?

**Comment by cbpowell** [comment]
Hmm, what's the execption? Is there any other info you can pull from the debugger?

**Comment by cyrilzakka** [comment]
log just says (lldb)

**Comment by cbpowell** [comment]
Well that's not a lot to go on, but are you sure your songNameLabel is an instance of MarqueeLabel? Check in Interface Builder to make sure you've set the Custom Class value to MarqueeLabel:

![screenshot 2015-04-26 19 14 03](https://cloud.githubusercontent.com/assets/593953/7340712/a1e6265e-ec48-11e4-9337-3abf67829c85.png)

It would immediately crash upon reaching the `songNameLabel.type = .Continuous` line if it's still a normal UILabel, as UILabel obviously doesn't have that property.

**Comment by cyrilzakka** [comment]
Thanks 😊 Forgot I'd declared them in IB
