### ISSUE TITLE
Bug: Font resets to System/default on Continuous Scroll

### ISSUE THREAD

**Issue by samsonho** [cbpowell/MarqueeLabel-Swift#5]
Hi, 

I have used your ObjC MarqueeLabel and now trying your swift version as a drop in replacement. Thank you for your work first of all!

My problem is that I have noticed that when the text scrolls past the end and back to the start again, the font of the text changes temporarily.

I use Avenir Next in my storyboard for the navigation title and when it scrolls back to the start the font MarqueeLabel temporarily uses a different font.

I have attached three screen shots to demonstrate what I am trying to describe.
1. Initial and correct size font (Notice the font of Shishigatanihonenicho...)
2. The text has scrolled, still ok.
3. The text has scrolled past the end and font has now changed (Notice the font of the same text above).

I hope that is sufficient for you to figure out if it is bug or not. I am happy to provide more detail if you require it.

Thanks,
Sam

**Comment by cbpowell** [comment]
Glad you find it useful! Good catch, it was definitely a bug. I think it resulted from when I was trying to merge the latest Objective-C version features into this Swift version, and I forgot to implement the getter/setters for the `text` and `attributedText` property overrides. The latest commit (bba4270) should fix it, let me know if it doesn't!
