### ISSUE TITLE
Question: When will be availbale via pod install?

### ISSUE THREAD

**Issue by szuniverse** [cbpowell/MarqueeLabel-Swift#8]
HI!

The swift version works fine! When will be available via pods?

**Comment by funkenstrahlen** [comment]
I would also like to use this via pod install!

**Comment by cbpowell** [comment]
Just added the new [v2.3.4 release](https://github.com/cbpowell/MarqueeLabel-Swift/releases/tag/2.3.4) as a Cocoapod!

**Comment by funkenstrahlen** [comment]
Works perfectly! Thanks 😃
